# Generated by Django 4.2.30 on 2026-06-13 07:53

import admissions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='extracurricular_activities',
            new_name='activities',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applicant_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant_document',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant_image',
        ),
        migrations.AddField(
            model_name='application',
            name='document',
            field=models.FileField(default='dummy.pdf', upload_to='documents/%Y/%m/', validators=[admissions.validators.validate_document_extension, admissions.validators.validate_file_size]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.ImageField(default='dummy.jpg', upload_to='photos/%Y/%m/', validators=[admissions.validators.validate_image_extension, admissions.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
